<a href="https://colab.research.google.com/github/Natali-bali/TensorFlow_Tutorial/blob/master/00_tesorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.5.0


## Introduction to tensors

### Create tensors with tf.constant()

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
matrix = tf.constant([[1,2,3],[4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

### Check the number of dimentions

In [ ]:
matrix.ndim

2

In [ ]:
# add data type
matrix2 = tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float32)

In [ ]:
matrix2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [ ]:
tensor = tf.constant([[[1,2],[2,3]],[[4,5],[6,7]], [[8,9],[10,11]]])

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### Create tensors with tf.Variable()

In [ ]:
#create same tensors
changeble_tensor = tf.Variable([1,2])
unchangable_tensor = tf.constant([1,2])


In [ ]:
changeble_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

In [ ]:
# change tensor
# changeble_tensor[0] = 7
# changeble_tensor

In [ ]:
# changeble_tensor[0].assign(7.)
# changeble_tensor

In [ ]:
changeble_tensor[0].assign(7)
changeble_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 2], dtype=int32)>

### Create random tensors

In [ ]:
# create random but same tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.uniform(shape=(3,2)) #uniform(square) distribution
random_2 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_2 = random_2.uniform(shape=(3,2)) #uniform(square) distribution

In [ ]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
random_3 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_3 = random_3.normal(shape=(3,2)) #normal distribution

In [ ]:
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

### Shuffle the data

In [ ]:
not_shuffled = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
not_shuffled.ndim, not_shuffled

(3, <tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12]]], dtype=int32)>)

In [ ]:
tf.random.set_seed(54)
shuffled = tf.random.shuffle(not_shuffled, seed = 54)
shuffled

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 9, 10],
        [11, 12]],

       [[ 5,  6],
        [ 7,  8]]], dtype=int32)>

In [ ]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape = (3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Create tensors from nparrays

In [ ]:
np_A = np.arange(1, 25, dtype = np.int16)

In [ ]:
np_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [ ]:
A  = tf.constant(np_A)
A

<tf.Tensor: shape=(24,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)>

In [ ]:
B = tf.constant(np_A, shape = (4,2,3))

In [ ]:
B

<tf.Tensor: shape=(4, 2, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]], dtype=int16)>

### Get info from tensors
- Shape
- Rank
- Axis
- Size

In [ ]:
X = tf.ones(shape = (2,3,4,5), dtype=tf.int16)

In [ ]:
X

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int16, numpy=
array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int16)>

In [ ]:
X[0]

<tf.Tensor: shape=(3, 4, 5), dtype=int16, numpy=
array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)>

In [ ]:
X[:,0]

<tf.Tensor: shape=(2, 4, 5), dtype=int16, numpy=
array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)>

In [ ]:
X[0,:2,3]

<tf.Tensor: shape=(2, 5), dtype=int16, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)>

In [ ]:
X[0,1:,1:3,0]

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[1, 1],
       [1, 1]], dtype=int16)>

In [ ]:
# get attrributes of our tensor
X.shape, X.ndim, tf.size(X), X.dtype, X.shape[-1]

(TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 tf.int16,
 5)

### Indexing and expanding tensors

In [ ]:
X[:1,:1,:1,]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int16, numpy=array([[[[1, 1, 1, 1, 1]]]], dtype=int16)>

### Reshape tensor


In [ ]:
X2 = tf.constant([[1,2], [3,4]])
X2.shape

TensorShape([2, 2])

In [ ]:
# Add extra dimention
X2 = X2[tf.newaxis, ...]
# X2 = X2[..., tf.newaxis]
# X2 = X2[:, :, tf.newaxis]

In [ ]:
X2.shape

TensorShape([1, 2, 2])

In [ ]:
X2

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [ ]:
X2 = tf.expand_dims(X2, axis = -1)

In [ ]:
X2.shape

TensorShape([1, 2, 2, 1])

### Tensors operations

In [ ]:
X = tf.constant([[1,2,3],[4,5,6]])
X2 = tf.constant([[1,2,3],[4,5,6]])

In [ ]:
X+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [ ]:
X*10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>

In [ ]:
#We can use built in functions
X = tf.multiply(X, 10)

In [ ]:
tf.multiply(X, X2) #dtypes shold be the same

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 10,  40,  90],
       [160, 250, 360]], dtype=int32)>

In [ ]:
X.shape, X2.shape

(TensorShape([2, 3]), TensorShape([2, 3]))

### Matrix multiplication

In [ ]:
# tf.matmul(X, X2)

In [ ]:
X = tf.constant([[1,2,3,4],[1,2,3,4]])
X2 = tf.constant([[1,2,3],[1,2,3],[1,2,3], [1,2,3]])
X.shape, X2.shape

(TensorShape([2, 4]), TensorShape([4, 3]))

In [ ]:
tf.matmul(X, X2) #last number from first matrix and first number from last matrix, same dim?
# for matrix numbers inside must match, output matrix has shape of outside numbers
#[2,4]@[4,3]=[2,3]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [10, 20, 30]], dtype=int32)>

In [ ]:
Y = X@X2 #same operation
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [10, 20, 30]], dtype=int32)>

In [ ]:
tf.tensordot(X, X2, axes = 1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [10, 20, 30]], dtype=int32)>

In [ ]:
#transpose (flipping axises) vs reshape (reorganize values)
tf.transpose(Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 10],
       [20, 20],
       [30, 30]], dtype=int32)>

In [ ]:
tf.reshape(Y, shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 10],
       [20, 30]], dtype=int32)>

### Change dtype of tensor

In [ ]:
X #default int or float32
#16 bit runs faster and uses less memory, we can improve performance

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [1, 2, 3, 4]], dtype=int32)>

In [ ]:
X = tf.cast(X, dtype = tf.int8)

In [ ]:
X

<tf.Tensor: shape=(2, 4), dtype=int8, numpy=
array([[1, 2, 3, 4],
       [1, 2, 3, 4]], dtype=int8)>

### Tensors aggregation

In [ ]:
E = tf.constant(np.random.randint(1,100,50))
E = tf.reshape(E, shape = (10,5))
E

<tf.Tensor: shape=(10, 5), dtype=int64, numpy=
array([[12, 29, 29, 28,  9],
       [92, 70,  3, 45, 21],
       [24, 22, 15, 34, 53],
       [27, 69, 94,  8, 40],
       [ 6, 66, 52, 14, 26],
       [86, 75, 29,  5,  1],
       [22, 51, 84, 90, 61],
       [82, 89, 96, 46, 29],
       [85, 31, 85, 25, 95],
       [68, 95, 56, 64, 78]])>

In [ ]:
tf.size(E), E.ndim, E.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 2, TensorShape([10, 5]))

In [ ]:
# find min (add word reduce)
#np.min(E)
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
#Find maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [ ]:
#Find mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
#Find sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2416>

In [ ]:
#Find standard deviation
tf.math.reduce_std(E)

TypeError: ignored

In [ ]:
E = tf.cast(E, dtype=tf.float32)
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=30.229416>

In [ ]:
# Find variance
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1100.0399 ,  583.41003, 1060.4099 ,  629.89   ,  822.20996],
      dtype=float32)>

In [ ]:
tf.math.reduce_variance(E)
#why results are different?

<tf.Tensor: shape=(), dtype=float32, numpy=913.81757>

### Find positional max and min

In [ ]:
tf.random.set_seed(42)
G = tf.random.uniform(shape = [50])

In [ ]:
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

### Squeezing tensor (removing single dimentions

In [ ]:
G = G[tf.newaxis, tf.newaxis, tf.newaxis, ...]

In [ ]:
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
 array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
       dtype=float32)>, TensorShape([1, 1, 1, 50]))

In [ ]:
tf.squeeze(G).shape


TensorShape([50])

### One hot encoding

In [ ]:
some_list = [0,1,2,3,4,5]
H = tf.one_hot(some_list, depth = 5)

In [ ]:
H

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#Specify values
H = tf.one_hot(some_list, depth = 5, on_value=2., off_value=3.)

In [ ]:
H

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[2., 3., 3., 3., 3.],
       [3., 2., 3., 3., 3.],
       [3., 3., 2., 3., 3.],
       [3., 3., 3., 2., 3.],
       [3., 3., 3., 3., 2.],
       [3., 3., 3., 3., 3.]], dtype=float32)>

In [ ]:
tf.sqrt(H)

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[1.4142135, 1.7320508, 1.7320508, 1.7320508, 1.7320508],
       [1.7320508, 1.4142135, 1.7320508, 1.7320508, 1.7320508],
       [1.7320508, 1.7320508, 1.4142135, 1.7320508, 1.7320508],
       [1.7320508, 1.7320508, 1.7320508, 1.4142135, 1.7320508],
       [1.7320508, 1.7320508, 1.7320508, 1.7320508, 1.4142135],
       [1.7320508, 1.7320508, 1.7320508, 1.7320508, 1.7320508]],
      dtype=float32)>

In [ ]:
tf.math.log(H)

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[0.6931472, 1.0986123, 1.0986123, 1.0986123, 1.0986123],
       [1.0986123, 0.6931472, 1.0986123, 1.0986123, 1.0986123],
       [1.0986123, 1.0986123, 0.6931472, 1.0986123, 1.0986123],
       [1.0986123, 1.0986123, 1.0986123, 0.6931472, 1.0986123],
       [1.0986123, 1.0986123, 1.0986123, 1.0986123, 0.6931472],
       [1.0986123, 1.0986123, 1.0986123, 1.0986123, 1.0986123]],
      dtype=float32)>

### Tensors and Numpy

In [ ]:
J = tf.constant(np.array([1.,2.,3.,4.]))

In [ ]:
# Converting back
np.array(J), type(np.array(J))

(array([1., 2., 3., 4.]), numpy.ndarray)

In [ ]:
#Or
J.numpy()

array([1., 2., 3., 4.])

### Getting access to GPU

In [ ]:
tf.config.get_visible_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Thu Jun  3 05:24:34 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   77C    P0    34W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
## When we have access to CUDA enabled GPU tensorflow will use it

### Exercises
1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.


In [ ]:
#1
scalar = tf.constant(3)
vector = tf.constant([1,2])
matrix = tf.constant([[1,2],[3,4]])
tensor = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]], dtype=int32)>)

In [ ]:
#2
l = [scalar, vector, matrix, tensor]
l2 = ['scalar', 'vector', 'matrix', 'tensor']

for item, n in zip(l,l2):
  print(n, ' shape: ', item.shape)
  print(n, ' rank: ', item.ndim)
  print(n, ' size: ', tf.size(item))


scalar  shape:  ()
scalar  rank:  0
scalar  size:  tf.Tensor(1, shape=(), dtype=int32)
vector  shape:  (2,)
vector  rank:  1
vector  size:  tf.Tensor(2, shape=(), dtype=int32)
matrix  shape:  (2, 2)
matrix  rank:  2
matrix  size:  tf.Tensor(4, shape=(), dtype=int32)
tensor  shape:  (2, 2, 2)
tensor  rank:  3
tensor  size:  tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
#3 Create two tensors containing random values between 0 and 1 with shape [5, 300].
tensor1 = tf.random.uniform(shape = (5,300), minval=0, maxval=1)
tensor1
tensor2 = tf.random.uniform(shape = (5,300), minval=0, maxval=1)
tensor2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.43555546, 0.52486527, 0.49674678, ..., 0.00552487, 0.3156761 ,
        0.22303641],
       [0.93881905, 0.02025807, 0.8929347 , ..., 0.47184265, 0.93879664,
        0.27382708],
       [0.8537835 , 0.287457  , 0.57827055, ..., 0.22605908, 0.62864304,
        0.28893173],
       [0.83130777, 0.13316286, 0.4270022 , ..., 0.96334374, 0.81353974,
        0.47423255],
       [0.20213544, 0.15954506, 0.9492575 , ..., 0.93022454, 0.31091654,
        0.41263437]], dtype=float32)>

In [ ]:
#4 Multiply the two tensors you created in 3 using matrix multiplication
tensor1*tensor2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[4.1740078e-01, 8.8221403e-03, 1.5677501e-01, ..., 3.7075176e-03,
        2.4222128e-01, 4.4887718e-02],
       [9.3146749e-02, 5.0140399e-04, 4.2184156e-01, ..., 4.5445400e-01,
        3.2232133e-01, 2.2260757e-01],
       [7.5286478e-02, 2.6767886e-01, 1.3260779e-01, ..., 9.3702003e-02,
        5.2202516e-03, 7.0464886e-03],
       [4.5567775e-01, 4.9296387e-02, 2.2514364e-01, ..., 8.3396196e-01,
        1.5981649e-01, 2.8260568e-01],
       [1.8119596e-01, 2.4391357e-02, 3.1900662e-01, ..., 5.3260678e-01,
        1.2729385e-01, 1.6529728e-01]], dtype=float32)>

In [ ]:
#Multiply the two tensors you created in 3 using dot product.
tensor1@tf.transpose(tensor2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.45296 , 74.09731 , 74.092186, 73.01437 , 73.156876],
       [74.90098 , 75.27091 , 77.775635, 74.37875 , 74.90591 ],
       [83.04034 , 79.46228 , 82.300026, 80.63679 , 78.7219  ],
       [76.86667 , 76.41696 , 79.00328 , 77.386116, 77.40252 ],
       [76.20902 , 74.707855, 79.07422 , 75.523506, 73.94785 ]],
      dtype=float32)>

In [ ]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tf.random.set_seed(42)
tensor3 = tf.random.uniform(shape = (224,224,3), minval = 0, maxval = 1, seed = 42)

In [ ]:
#Find the min and max values of the tensor you created in 6.
tf.reduce_min(tensor3), tf.reduce_max(tensor3)

(<tf.Tensor: shape=(), dtype=float32, numpy=1.7404556e-05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999901>)

In [ ]:
#Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor4 = tf.expand_dims(tensor3, axis = 0)
tensor4.shape

TensorShape([1, 224, 224, 3])

In [ ]:
tf.squeeze(tensor4).shape

TensorShape([224, 224, 3])

In [ ]:
#Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor5 = tf.constant([1,3,5,3,7,6,78,34,65,23])
tf.argmax(tensor5)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [ ]:
# One-hot encode the tensor you created in 9.
tensor5 = tf.cast(tensor5, dtype=tf.int32)
tensor5
tf.argmax(tensor5)
tf.one_hot(tensor5, depth = tf.reduce_max(tensor5))

<tf.Tensor: shape=(10, 78), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 

### Extensions
- Read through the list of TensorFlow Python APIs, pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
- Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
- How would you calculate your grocery bill for the month and for the year using tensors?
- Go through the TensorFlow 2.x quick start for beginners tutorial (be sure to type out all of the code yourself, even if you don't understand it).
- Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
- Watch the video "What's a tensor?" - a great visual introduction to many of the concepts we've covered in this notebook.